name: image_editor
description: Edit your image data and output to file/memory on Android and iOS.
version: 1.1.0
homepage: https://github.com/fluttercandies/flutter_image_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: com.fluttercandies.image_editor
        pluginClass: ImageEditorPlugin
      ios:
        pluginClass: ImageEditorPlugin
      macos:
        pluginClass: ImageEditorPlugin
